# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/api/races

###

GET http://localhost:8080/api/races/4380766d-ae5b-4c48-8e89-8a45e6a11f12

###

GET http://localhost:8080/api/races?totalFeatures=8

###

GET http://localhost:8080/api/races/compare?race1=cc4613c8-644b-42c6-ab62-c4828d97dcf4&race2=57294557-e2ce-461e-ad69-b622dcc6ab74

###

DELETE  http://localhost:8080/api/races/cc4613c8-644b-42c6-ab62-c4828d97dcf4

###
